bug fix:
  - "bug"
  - "fix"
  - "error"

level 1:
  - "level[\\s_-]?1"

level 2:
  - "level[\\s_-]?2"

level 3:
  - "level[\\s_-]?3"

gssoc25:
  - "gssoc25"

good first issue:
  - "good first issue"

enhancement:
  - "enhancement"
  - "improvement"

feature request:
  - "feature request"
  - "suggestion"
  - "new feature"

documentation:
  - "documentation"
