bug fix:
  patterns:
    - pattern: 'bug|fix|error'
      flags: 'i'

level 1:
  patterns:
    - pattern: 'level[\s_-]?1'
      flags: 'i'

level 2:
  patterns:
    - pattern: 'level[\s_-]?2'
      flags: 'i'

level 3:
  patterns:
    - pattern: 'level[\s_-]?3'
      flags: 'i'

gssoc25:
  patterns:
    - pattern: 'gssoc25'
      flags: 'i'

good first issue:
  patterns:
    - pattern: 'good first issue'
      flags: 'i'

enhancement:
  patterns:
    - pattern: 'enhancement|improvement'
      flags: 'i'

feature request:
  patterns:
    - pattern: 'feature request|suggestion|new feature'
      flags: 'i'
