bug fix:
  - "(?i)bug"
  - "(?i)fix"
  - "(?i)error"

level 1:
  - "(?i)level[\\s_-]?1"

level 2:
  - "(?i)level[\\s_-]?2"

level 3:
  - "(?i)level[\\s_-]?3"

gssoc25:
  - "(?i)gssoc25"

good first issue:
  - "(?i)good first issue"

enhancement:
  - "(?i)enhancement"
  - "(?i)improvement"

feature request:
  - "(?i)feature request"
  - "(?i)suggestion"
  - "(?i)new feature"

documentation:
  - "(?i)documentation"