bug fix:
  - 'fix/**'
  - '**/bugfix/**'

level 1:
  - 'level1/**'

level 2:
  - 'level2/**'

level 3:
  - 'level3/**'

gssoc25:
  - 'gssoc25/**'

good first issue:
  - 'good-first-issue/**'

documentation:
  - 'docs/**'
  - '**/*.md'

enhancement:
  - 'enhancement/**'

feature request:
  - 'feature-request/**'
  - 'feature/**'
  - 'request/**'
  - 'suggestion/**'
