name: 💬 Auto Comment on Issue Close

on:
  issues:
    types:
        - closed

permissions:
  issues: write
  contents: read

jobs:
  comment-on-close:
    runs-on: ubuntu-latest
    steps:
      - name: 💬 Post comment on closed issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const issueTitle = context.payload.issue.title;
            const issueAuthor = context.payload.issue.user.login;
            const closer = context.payload.sender.login;

            const owner = context.repo.owner;

            if (closer === owner) {
              console.log(`Issue closed by repo owner (${owner}). Skipping comment.`);
              return;
            }

            const comment = `👋 Hi @${issueAuthor}!
            Thank you for your contribution! The issue "${issueTitle}" has been closed.
            If you still face any problems or have more suggestions, feel free to open a new issue. Happy coding! 🚀🚀`;

            await github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });