name: 🔒 Auto Comment on PR Closed

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write
  contents: read

jobs:
  comment-on-pr-close:
    runs-on: ubuntu-latest
    steps:
      - name: 💡 Check if PR closer is not the repo owner
        id: check
        run: |
          if [ "${{ github.event.pull_request.user.login }}" != "${{ github.repository_owner }}" ]; then
            echo "is_contributor=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_contributor=false" >> "$GITHUB_OUTPUT"
          fi

      - name: 💬 Post comment on closed PR
        if: steps.check.outputs.is_contributor == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const prTitle = context.payload.pull_request.title;
            const prCloser = context.actor;
            const prAuthor = context.payload.pull_request.user.login;
            const merged = context.payload.pull_request.merged;

            let message;
            if (merged) {
              message = `🎉 Congratulations @${prAuthor} — your pull request titled **"${prTitle}"** has been merged by @${prCloser}! 

              Thank you for your contribution! 🧡`;
            } else {
              message = `📪 Your pull request titled **"${prTitle}"** was closed by @${prCloser}. 

              If you have any questions, feel free to ask. Thanks for the effort, @${prAuthor}! 🙌`;
            }

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
