name: 💬 Auto Comment on PR Opened

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 💡 Check if author is not the repo owner
        id: check
        run: |
          if [ "${{ github.event.pull_request.user.login }}" != "${{ github.repository_owner }}" ]; then
            echo "is_contributor=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_contributor=false" >> "$GITHUB_OUTPUT"
          fi

      - name: 💬 Post comment on new PR
        if: steps.check.outputs.is_contributor == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const prTitle = context.payload.pull_request.title;
            const prAuthor = context.payload.pull_request.user.login;

            const comment = `👋 Hi @${prAuthor}!

            Thanks for opening this pull request titled **"${prTitle}"**.
            Our team will review it as soon as possible. Please make sure your PR follows the contributing guidelines and passes all checks ✅.

            Happy contributing! 🚀`;

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
