name: Close Old Issues and PRs

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    close-stale-items:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write

        steps:
            - name: Close stale issues and PRs
              uses: actions/stale@v9
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  days-before-stale: 30
                  days-before-close: 7
                  stale-issue-message: >
                      This issue has been automatically marked as stale due to 30 days of inactivity. If this is still relevant, feel free to comment or update — otherwise, it will be closed soon.

                  close-issue-message: >
                      Closing this issue due to inactivity. Feel free to reopen if needed.
                  stale-pr-message: >
                      This PR has been automatically marked as stale after 30 days of inactivity. It will be closed if no further updates are made.
                  close-pr-message: >
                      This PR was closed due to inactivity. Reopen or push new commits to resume.
                  exempt-issue-labels: "pinned,security,important"
                  exempt-pr-labels: "work-in-progress,do-not-close"
                  remove-stale-when-updated: true
