name: Duplicate Issue Checker

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  check-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: Check for duplicate issues
        uses: actions/github-script@v7
        with:
          script: |
            const issueTitle = context.payload.issue.title.toLowerCase();
            const issueNumber = context.payload.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            console.log(`Checking for duplicates of: "${issueTitle}"`);

            // Search for similar issues
            const { data: issues } = await github.rest.search.issuesAndPullRequests({
              q: `repo:${repoOwner}/${repoName} is:issue is:open in:title "${issueTitle}"`,
            });

            // Filter out the current issue
            const possibleDuplicates = issues.items.filter(issue => issue.number !== issueNumber);

            if (possibleDuplicates.length > 0) {
              const commentBody = [
                "🔍 **Possible duplicate issues found:**",
                "",
                ...possibleDuplicates.slice(0, 5).map(issue => `- [#${issue.number}](${issue.html_url}) - ${issue.title}`),
                "",
                "Please review the above issues to see if your problem has already been reported. If so, you may want to add a comment there instead."
              ].join('\n');

              // Comment on the issue
              await github.rest.issues.createComment({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                body: commentBody
              });

              console.log("Commented with possible duplicates.");
            } else {
              console.log("No duplicates found.");
            }
