name: 🚨 Detect Duplicate Issues

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  issues: write
  contents: read

jobs:
  detect-duplicates:
    name: 🔍 Detect Similar Issues
    runs-on: ubuntu-latest

    steps:
      - name: Detect similar issues
        uses: actions-cool/issues-similarity-analysis@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          since-days: 100

          filter-threshold: 0.75

          title-excludes: "bug,fix,issue,request"

          show-mentioned: false

          comment-title: "🔁 Possible Duplicate Issue Detected"
          comment-body: |
            Hey @{context.payload.issue.user.login}, 👋 Thanks for opening this issue.

            Based on the title and content, this issue **might be related to the following**:

            {related-issues}

            Please review and consider adding your input to the linked issue(s) if applicable. If this is indeed a new issue, feel free to clarify, and we’ll keep it open.