name: 🚨 Detect Duplicate Issues

on:
  issues:
    types: [opened, edited]

jobs:
  detect-duplicates:
    name: 🔍 Detect and Handle Duplicates
    runs-on: ubuntu-latest

    steps:
      - name: Check for similar issues
        uses: actions-cool/issues-similarity-analysis@v1
        with:
          # GitHub token for API access (automatically provided by GitHub)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Include both issue title and body in similarity analysis
          title-include: true
          body-include: true

          # Minimum similarity threshold (0.7 = 70% match)
          similarity-threshold: 0.7

          # Only search open issues (skip closed ones)
          state: open

          # Add a label if similar issues are found
          add-label: duplicate

          # Custom comment title shown in issue
          comment-title: "🔁 Possible Duplicate Issue Detected"

          # Comment body with markdown and dynamic placeholders
          comment-body: |
            Hey @{{ author }} 👋 Thanks for submitting an issue!

            Based on our analysis, your issue may be similar to the following existing issue(s):

            {{ similar_issues }}

            Please check them before continuing. If your issue is indeed different, feel free to clarify in a comment and we’ll take another look.

          # Avoid commenting multiple times if issue already has the "duplicate" label
          check-label: true

          # Limit how many similar issues are listed (default is 3)
          max-number: 3
