name: Duplicate Issue Detector

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  detect-duplicate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Detect duplicate issues
        uses: actions-cool/issues-similarity-analysis@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          since-days: 100
          filter-threshold: 0.7
          comment-title: "🔁 Possible Duplicate Issue Detected"
          comment-body: |
            Hey @{author}, 👋 Thanks for opening this issue.

            Based on the title and content, this issue **might be related to the following**:

            {related-issues}

            Please review and consider adding your input to the linked issue(s) if applicable. If this is indeed a new issue, feel free to clarify, and we’ll keep it open.
          show-mentioned: false
          skip-comment-if-no-related: true
