name: Duplicate Issue Checker

on:
  issues:
    types: [opened, reopened, edited]

permissions:
  issues: write
  contents: read

jobs:
  check-duplicate:
    name: Check for Duplicate Issues
    runs-on: ubuntu-latest
    steps:
      - name: Search for similar open issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = context.payload.issue.title.toLowerCase();
            const issueNumber = context.payload.issue.number;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            // Perform a broader search using parts of the title
            const searchQuery = issueTitle
              .split(' ')
              .filter(word => word.length > 3)
              .slice(0, 5)
              .join(' ');

            const searchResults = await github.rest.search.issuesAndPullRequests({
              q: `repo:${repoOwner}/${repoName} is:issue is:open in:title ${searchQuery}`
            });

            const possibleDuplicates = searchResults.data.items.filter(issue =>
              issue.number !== issueNumber &&
              issue.title.toLowerCase().includes(searchQuery)
            );

            if (possibleDuplicates.length > 0) {
              const commentBody = [
                "🔍 **Possible duplicate issues found:**",
                "",
                ...possibleDuplicates.slice(0, 5).map(issue => `- [#${issue.number}](${issue.html_url}) - ${issue.title}`),
                "",
                "Please review the above issues to see if your problem has already been reported. If so, consider contributing to the existing discussion."
              ].join('\n');

              await github.rest.issues.createComment({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueNumber,
                body: commentBody
              });
            } else {
              console.log("✅ No duplicates found.");
            }
