name: 🏷️ Issue Auto Labeler

on:
  issues:
    types: [opened, edited]

jobs:
  autolabel:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.3
        with:
          configuration-path: .github/labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          enable-versioned-regex: true
