- name: Remove unauthorized labels
  uses: actions/github-script@v7
  with:
    github-token: ${{ github.token }}  # ✅ Use this unless you absolutely need a PAT
    script: |
      const actor = context.actor;
      const label = context.payload.label.name;
      const issueNumber = context.issue.number;
      const repoOwner = context.repo.owner;
      const repoName = context.repo.repo;

      const allowedActors = [
        repoOwner,
        'github-actions[bot]',
      ];

      const isFork = context.payload.pull_request ? context.payload.pull_request.head.repo.fork : false;

      if (!allowedActors.includes(actor) || isFork) {
        console.log(`❌ Label "${label}" added by unauthorized actor @${actor}. Removing...`);

        await github.rest.issues.removeLabel({
          owner: repoOwner,
          repo: repoName,
          issue_number: issueNumber,
          name: label
        });

        await github.rest.issues.createComment({
          owner: repoOwner,
          repo: repoName,
          issue_number: issueNumber,
          body: `⚠️ Label \`${label}\` was removed. Only **@${repoOwner}** or trusted bots can manage labels.`
        });
      } else {
        console.log(`✅ Label "${label}" added by authorized actor @${actor}`);
      }
